### ISSUE TITLE
Plots show different results

### ISSUE THREAD

**Issue by yu-ting-py** [Trel725/plasmon-meep#2]
Thanks for your nice scripts! I try to reproduce your results by simply following your instructions in README.md. But I got different results from yours. What is the problem here? 
![Figure_2](https://user-images.githubusercontent.com/42253517/86767280-09a3d200-c04c-11ea-8434-bc5cf1b2a6dc.png)
![Figure_1](https://user-images.githubusercontent.com/42253517/86767283-09a3d200-c04c-11ea-8993-7b91306c65ff.png)

**Comment by Trel725** [comment]
Hello, have you tried pressing j or k while first plot is active? You should be able to navigate through  various frequencies, with different enhancement maps for each frequency.

**Comment by yu-ting-py** [comment]
After trying to press j or k, I can switch to different frequencies. Thanks!

**Comment by Trel725** [comment]
You're welcome. Feel free to re-open the issue if anything else is unclear.
