### ISSUE TITLE
non-uniform grid in meep

### ISSUE THREAD

**Issue by Nikolaos-Matthaiakakis** [Trel725/plasmon-meep#4]
Hello and thank you very much for sharing your nice scripts. I recently ran into this discussion [(https://github.com/NanoComp/meep/issues/914)] in the meep issues section.

I am trying to create a non-uniform grid in my code so I am very interested to compare with your method.

In my code I do the following

1) Run a reference simulation without my geometry but including a block of air that has been transformed using mat_air.transform(scale) where mat_air is my air block and scale is the value I use to stretch my structure (scale*x for example)

2) I rerun the simulation this time including my both the air block with the transformed material properties and my stretched structure (scale*x for example) which also has transformed material properties as mat.transform(scale) .

This method seems to work but I am a bit confused as I originally thought that instead of mat_air.transform(scale) I had to use mat_air.transform(1/scale), something that gave wrong results.

Could you please share your experience on this matter?

Thank you very much

**Comment by Trel725** [comment]
Dear Nikolaos,

I am glad you are interested in the same problem I am. The reason you need to scale by scale instead of its reciprocal is in the Jacobian:
Suppose you want to stretch X-axis by factor of 2, then your new variables will be
x' = 2x
y' = y
i.e. stretching something is equivalent to multiplying by two, Since Jacobian is x'_i/x_j, it is:
J = (2 0; 0 1), which I think answers the question. I suppose you had a look at the [paper](http://math.mit.edu/~stevenj/18.369/coordinate-transform.pdf).

About my experience, I think it worked quite well for simple materials, but not for dispersive ones I am interested in. If you'd like we can set up some geometry and both calculate it to compare our results. Unfortunately, I still did no find the good answer why this method fails for dispersive materials.

Regards

**Comment by Nikolaos-Matthaiakakis** [comment]
Dear Andrii,

Thank you very much for the reply. Its true I also want to use it for dispersive materials like graphene. In general I feel like a non uniform grid is the only thing missing from Meep.

After looking into the paper, the definition of transform in the user interface, and your reply I now understand why it works this way.

My code produces the correct frequency response but higher intensity for scattering from Dielectric sphere so I guess I need to work on it a bit more. I was wondering if you could also share your code with the transformation on your github. I think many users of Meep face issues with this transformation.

Once again thanks for the reply. I will let you know if the transform ever works for graphene.

Best wishes
Nikolaos

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Trel725** [comment]
Dear Nikolaos, 

I am totally agree with you that variable grid resolution is probably the most desired missing feature in MEEP. I suppose that developers of MEEP utilize it for quite different purposes so this feature is of interest to only smaller subset of users like we are.

I am not sure about two details of these simulations:

1)  What is the behavior of the border between stretched and non-stretched areas? Can we guarantee that it does not influence the results?
2) How the fields in the stretched area interact with fields in normal area? Again, is there any potential problems because of these interactions?

Of course, these issues can be probably resolved by stretching the whole computational cell, which is equivalent to using Yee lattice with cuboid instead of cubic cells. However, I have seen some strange effects in that case and now sure if sources, monitors and PML will work correctly in the stretched space.

I will definitely clean up and publish my codes (hopefully during couple of days) although they do not work very well for now.

Good luck with simulating graphene, this is a truly nontrivial task. I will be very glad to see your results.

Regards,
Andrii

**Comment by Nikolaos-Matthaiakakis** [comment]
Dear Andrii,

I understand your worries about how this method can affect simulation results. I also obtained weird results when stretching the entire simulation cell. By the way, how small was the Courant factor that you used?

Thank you for sharing your code on this, I am looking forward to it.

Regarding Meep, I will try to write a request for a variable grid either on an existing or new github issue. I have worked a lot with lumerical fdtd and I can say that this type of grid can make simulating plasmonics very easy and without the need of high computational resources. It works well with graphene too.

Best wishes
Nikolaos

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Nikolaos-Matthaiakakis** [comment]
I have included a non-uniform grid request in the meep GitHub page. I am providing a link just in case it is of interest to anyone reading this discussion.

https://github.com/NanoComp/meep/issues/1442

**Comment by Nikolaos-Matthaiakakis** [comment]
So I played around a bit. I realized that you need to be extremely careful about the size of the air block, and the distance of the stretched plasmonic structure from the PML (or the boundary if you don't use PML). Maybe this could help you with the issue you are facing.

**Comment by smartalecH** [comment]
> About my experience, I think it worked quite well for simple materials, but not for dispersive ones I am interested in. If you'd like we can set up some geometry and both calculate it to compare our results. Unfortunately, I still did no find the good answer why this method fails for dispersive materials.

Did you transform your dispersion profile too?

**Comment by Trel725** [comment]
@Nikolaos-MAtthaiakakis, sorry for late reply. Unfortunately I still didn't manage to clean up the code and share it but hope to do it during weekend. Thank you for opening the issue although I do not believe that this feature will be implemented in reasonable time.

I do not access to codes now, but if I did not forget anything I have used Courant factor 0.5/scale. I will have a look at my notes and respond later if that isn't true.

@smartalecH, excuse me, but I am not sure which dispersion profile do you mean?  According to Steven Johnson it is enough to transform epsilon (https://github.com/NanoComp/meep/issues/914#issuecomment-501252172). I did not do anything more than calling .transform on all materials in the stretched region.

**Comment by Nikolaos-Matthaiakakis** [comment]
Thank you for the reply. I am also still fighting to make this work with graphene but fields diverge. It will probably take a while.

Edit: well it seems like it works. I got a graphene plasmon peak that agrees well with the one I get from the BEM code. Haven't done full convergence test yet but for 50nm original dx,dy,dz and a 10 times stretch the result was quite promising. Only thing that worries me is that even though the shape and frequency of the peak is fine, the actual value of the scattering cross section is off..

**Comment by Trel725** [comment]
Dear Nikolaos,

It is nice to hear you've reached some success with that methods. Probably it is already too late, but I have added my codes to repository, although they do no work very well. 

How did you calculate your cross-section? 

Regards,
Andrii

**Comment by Nikolaos-Matthaiakakis** [comment]
Thank you, I calculate it with the same method as used in the mie example in the tutorial/basics. The problem is that the monitors need to be inside or partially inside the transformed air block in this situation. I will have a look at your code as well in order to see if there are any differences.

**Comment by Nikolaos-Matthaiakakis** [comment]
Just to give an update. I am now getting some nice graphene peak that agrees well with my BEM simulations (I use a 20 times stretch). The problem is that at the high and low frequency limits of the simulation i get some noise which seems to originate from the coordinate transform

![Untitled](https://user-images.githubusercontent.com/58590846/102240801-ed606700-3f00-11eb-98b4-56dd44593b35.jpg)

This is my simulation region. I get similar results when extending the transformed air all the way to or within the PML boundaries.

![Untitled2](https://user-images.githubusercontent.com/58590846/102240978-213b8c80-3f01-11eb-8b0e-71bc17791860.jpg)

By the way, I noticed that in your example you set split_chunks to uneven in both simulations. I have noticed that sometimes this gives me weird spectra except if I load the same chunks for both simulations. Have you compared against an evenly split simulation?

edit: the problem was fixed by increasing the sx,sy simulation cell size. It might have been due to reflections from the PML

![Untitled](https://user-images.githubusercontent.com/58590846/102250406-35d15200-3f0c-11eb-9a67-4cc4dc212e3a.jpg)

**Comment by Trel725** [comment]
Dear Nikolaos,

Your results are great! It my old dream to see coordinate stretching finally working in MEEP. Moreover, 20 is a very significant factor and probably the only realistic way to simulate 2d materials. I stuck on stretching factor about 2 when was working on it.

Also, thank you for noting about splitting, I have not think about it and will give it another try.

Is your graphene model dispersive? 

It would be very nice to make a pull request to MEEP documentation with your results or at least to create a repository. I am sure it will be very useful for many researchers.

Kind regards,
Andrii

**Comment by Nikolaos-Matthaiakakis** [comment]
Dear Andrii,

Thank you, I will probably simplify the code and make it public since its true that it could be very useful. The result is good indeed although to fully converge it needs a bit more stretching :D to make the thickness closer to 1nm than 5nm that it currently is, but i simply haven't done it due to the computational time, as I already now know that it works (I compared with a BEM code for both 5nm and 0.34nm thickness). I am using a simple Drude model for graphene (similar to the one used in Lumerical FDTD) so its accurate only for the intraband response. I still sometimes get some nasty reflections(?) due to the transform as in the first picture of the previous post, but they are fixed when adjusting the simulation region and the transformed region. Placement of the monitors might be important too.

Now I have a new dreaded issue to fight... https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg06648.html 

Best wishes
Nikolaos

**Comment by Nikolaos-Matthaiakakis** [comment]
So I uploaded some code about this here https://github.com/Nikolaos-MAtthaiakakis/meep_graphene (should be up in a few minutes). Let me know if something is confusing or you have anything to add/fix.

**Comment by Trel725** [comment]
Dear Nikolaos, 

Thank you very much for your code, I am sure it will be useful for many MEEP users.

Regards
